import type { Metadata } from "next";
import "./globals.css";
import Header from "./componentes/header"; 
import Footer from "./componentes/footer";
import BotaoBaixeApp from "./componentes/botaoBaixeApp";


export const metadata: Metadata = {
  title: "CCR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Footer/>
        <BotaoBaixeApp/>
      </body>
    </html>
  );
}
